### PR TITLE
Update web3 to 1.2.x

### PR DESCRIPTION
**Pull request by dmihal**
Background:
I'm using this library for my project (Burner Wallet 2), and I'm trying to reduce the size of the compiled bundle of the app. The largest cause of bundle inflation is coming from us bundling many different versions of web3, since different libraries all have different dependencies.

-----
This PR updates web3 to version 1.2, which is the LTS version. It also updates abi-decoder to bring its web3 version inline. `bignumber.js` is no longer bundled in with web3, so it is added to the devDependencies so the tests will pass.

### CODE REVIEW

**Comment by drortirosh** [comment]
@nventuro ? 
LGTM, but I think you're more versed with web3 versions.

**Comment by dmihal** [comment]
Awesome! I'm guessing I need one of you guys to merge it? @nventuro @drortirosh

**Comment by dmihal** [comment]
@drortirosh Will this be published to NPM soon?

**Comment by drortirosh** [comment]
@dmihal : it is now published (as v0.4.2)

**Pull request merged**
